#!/bin/bash
# =================================================================
# dtdns-updater - Script to update dtdns hostname with current ip
# =================================================================
# @authors: 	Alle <alle@inventati.org>
#		Massimo Barbieri <massimo@fsfe.org>
#		(Add your name if you contribute)
# @Mantainer: Alle alle@inventati.org
# @copyright 2013 GNU GPLv3
# =================================================================
# This script is free software; you can redistribute it and/or
# modify it under the terms of the GNU GENERAL PUBLIC LICENSE
# License as published by the Free Software Foundation; either 
# version 3 of the License, or any later version.
# 
# You should have received a copy of the GNU General Public 
# License along with this library.
# If not, see <http://www.gnu.org/licenses/>.
###################################################################

# Variables that you have to configure
HOST=hostname
DOMAIN=mydomain.com
PASSWD=password
#############################

# Exit:
# 0 = Still IP
# 1 = Error to check IP
# 2 = Change IP

IPADDR=$(curl myip.dtdns.com)
VALIDATOR=$(echo $IPADDR | awk -F '.' '$1 < 255 && $2 < 255 && $3 < 255 && $4 < 255')

if [ -z "$VALIDATOR" ] ; then
        
	echo "Cannot check my ip at myip.dtdns.com"
	exit 1
fi

LASTIP=$(nslookup $HOST.$DOMAIN ns1.darktech.org | grep -A1 "$HOST" | grep Address | awk '{print $2 }')

TAG="DTDNS-UPDATER"

if [ "$IPADDR" != "$LASTIP" ]; then
	echo -e "GET /api/autodns.cfm?id=$HOST&pw=$PASSWD&client=BSD HTTP/1.1\nHost: www.dtdns.com\nUser-Agent: bash\n\n" | \
         nc www.dtdns.com 80 > /dev/null 2>&1
	echo "`date` - Sent ip change request to dtdns (from $LASTIP to $IPADDR)"
	logger "Sent ip change request to dtdns (from $LASTIP to $IPADDR)" -t $TAG
	exit 2
else
	echo "`date` - Still IP $IPADDR"
	exit 0
fi
